module.exports = [
    'expansion',
    'insert',
    'inserts',
    'organizer',
    'promo',
    'big box',
    'age of innovation',
    'upgrade',
    'replacement',
    'mini expansion',
    'sleeve',
    'pack',
    'tile',
    'tray',
    'deluxe',
    'storage',
    'components',
    'bits',
    'wooden',
    'metal',
    'standee',
    '3d',
    'overlay',
    'meeple',
    'compatible',
    'accessory',
    'fan expansion',
    'box',
    'bundle',
    'bundle includes',
    'bundle with',
    'extra',
    'addon',
    'insert organizer',
    'magnet',
    'stickers',
  ];